name: Android (arm64)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HERMES_WS_DIR: /home/runner/work/hermes_builder/hermes_builder

    steps:
    - uses: actions/checkout@v3
    - name: Apt Install
      run: sudo apt-get install ninja-build --yes --quiet
    - name: Build
      run: sh ./android.sh
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: hermes
        path: |
          ./build/lib/libhermesvm_a.a
          ./build/jsi/libjsi.a
          ./build/bin/shermes
