name: macOS (arm64-debug)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Brew Install
      run: brew install ninja
    - name: Build
      run: sh ./macos_debug.sh
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: hermes
        path: |
          ./build/lib/libhermesvm_a.a
          ./build/jsi/libjsi.a
          ./build/bin/shermes
